// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClfUHXoRIcG8vTWbbdxbEST_g_kP6dGGI',
    appId: '1:125039007022:web:1233879962dfeb212fd6bf',
    messagingSenderId: '125039007022',
    projectId: 'aurora-music-feefd',
    authDomain: 'aurora-music-feefd.firebaseapp.com',
    storageBucket: 'aurora-music-feefd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhoDXym2wZmYE6L76QOmw5g69iuTok1dg',
    appId: '1:125039007022:android:f1df59c1ffc562622fd6bf',
    messagingSenderId: '125039007022',
    projectId: 'aurora-music-feefd',
    storageBucket: 'aurora-music-feefd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq4PrnMrdx7xutbfqTCEJUrqxTeQXaXgQ',
    appId: '1:125039007022:ios:c923d9ca7b2715622fd6bf',
    messagingSenderId: '125039007022',
    projectId: 'aurora-music-feefd',
    storageBucket: 'aurora-music-feefd.firebasestorage.app',
    iosBundleId: 'com.example.auroraMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq4PrnMrdx7xutbfqTCEJUrqxTeQXaXgQ',
    appId: '1:125039007022:ios:c923d9ca7b2715622fd6bf',
    messagingSenderId: '125039007022',
    projectId: 'aurora-music-feefd',
    storageBucket: 'aurora-music-feefd.firebasestorage.app',
    iosBundleId: 'com.example.auroraMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClfUHXoRIcG8vTWbbdxbEST_g_kP6dGGI',
    appId: '1:125039007022:web:ae394fc945f43d5d2fd6bf',
    messagingSenderId: '125039007022',
    projectId: 'aurora-music-feefd',
    authDomain: 'aurora-music-feefd.firebaseapp.com',
    storageBucket: 'aurora-music-feefd.firebasestorage.app',
  );
}
